#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ load("@ytt:json", "json")
#@ name = json.decode(data.values.bom)["rabbitmq-operator"]["containers"][1]["name"]
#@ version = json.decode(data.values.bom)["rabbitmq-operator"]["containers"][1]["version"]
#@ image = name + ":" + version

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: veba-rabbit
  namespace: vmware-system
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "vmware-functions"
spec:
  image: #@ image
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
  replicas: 1
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: vmware-functions
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: veba-rabbit
    namespace: vmware-system
  delivery:
    retry: 2
    backoffPolicy: linear