builds:
  - id: router
    dir: cmd/router # default is .
    # main: .
    env:
      - GOPRIVATE=*.vmware.com
    flags:
      - -tags
      - netgo
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X main.commit={{.Env.KO_COMMIT}}
      - -X main.version={{.Env.KO_TAG}}
