# Perform "exit 1" if PR title starts with "WIP" to block accidental merges
name: Check "WIP" in PR Title

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - name: Check WIP in PR Title
        uses: embano1/wip@e83c03c8f4696b0cef273d83115521b26ebb8bec # v1
