name: Release VMware Event Router

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash
    working-directory: ./vmware-event-router

jobs:
  modules:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: verify modules are up2date/unchanged
        run: |
          make vendor
          [[ -z $(git status -s) ]] || (echo 'git dirty: modified and/or untracked'; git status -s; false)
  build-push:
    runs-on: ubuntu-latest
    needs: modules
    steps:
      - name: checkout source (master branch)
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: log in to Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
        run: echo "${DOCKER_SECRET}" | docker login -u "${DOCKER_USER}" --password-stdin
      - name: test, build, tag and push image
        run: make release
