name: Greeting

on:
  issues:
    types: ["opened"]

jobs:
  greeting:
    name: Send Greeting
    runs-on: ubuntu-latest
    # only send message to users not (yet) associated with repo
    # https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
    if: github.event.issue.author_association == 'NONE'

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        with:
          fetch-depth: 1

      - name: Render template
        id: template
        uses: chuhlomin/render-template@f828bb5c72a3e3af89cb79808cea490166c6f1ce # v1.4
        with:
          template: .github/comment-template.md
          vars: |
            author: ${{ github.actor }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae # v1.4.5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.template.outputs.result }}
