name: VMware Event Router Linting

# triggered on every push and PRs but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "vmware-event-router/**"
  push:
    paths:
      - "vmware-event-router/**"

jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        go-version: ["1.17"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # v2.5.2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest

          # Optional: working directory, useful for monorepos
          working-directory: vmware-event-router

          # Optional: golangci-lint command line arguments.
          args: --build-tags unit,integration -v --timeout 3m

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
