name: VMware Event Router Build Verification

# triggered on every PRs to verify builds but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'vmware-event-router/**'
  schedule:
  # runs daily
  - cron: '0 0 * * *'

# run all jobs with these defaults, unless specified otherwise
defaults:
  run:
    shell: bash
    working-directory: ./vmware-event-router

jobs:
  binaries:
    name: Build binaries
    strategy:
      matrix:
        go-version: ["1.17"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
        with:
          go-version: ${{ matrix.go-version }}
        id: go
        
      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@79d4afbba1b4eff8b9a98e3d2e58c4dbaf094e2b # v2.8.1
        with:
          version: latest
          args: release --rm-dist --snapshot
          workdir: vmware-event-router
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive run artifacts
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: dist
          path: |
            vmware-event-router/dist/router_Linux_*.tar.gz
            vmware-event-router/dist/checksums.txt
          retention-days: 1

  image:
    name: Verify Release ko artifact (no upload)
    strategy:
      matrix:
        go-version: ["1.17"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20
    env:
      KO_DOCKER_REPO: us.gcr.io/daisy-284300/veba # .../router@sha256:

    steps:
      - name: Setup ko
        uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
        with:
          go-version: ${{ matrix.go-version }}
        id: go
        
      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Get short COMMIT and TAG
        run: |
          echo "KO_COMMIT=$(echo -n $GITHUB_SHA | cut -c -8)" >> $GITHUB_ENV
          echo "KO_TAG=$(basename "${{ github.ref }}")" >> $GITHUB_ENV
          
      - name: Build image (no push)
        run: |
          # build, push and create release YAML
          ko resolve --platform=linux/arm64,linux/amd64 --push=false --tags ${KO_TAG},${KO_COMMIT},latest -BRf deploy/event-router-k8s.yaml > release.yaml

      - name: Archive run artifacts
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: release
          path: |
            ./vmware-event-router/release.yaml
          retention-days: 1