name: "Close stale issues"
on:
  schedule:
  # runs daily
  - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        # for issues and PRs        
        days-before-stale: 90
        days-before-close: 30
        exempt-issue-labels: 'awaiting-approval,work-in-progress,wip'

        # issues
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        close-issue-message: 'Closing issue due to inactivity. Please reopen if needed'
        stale-issue-label: 'stale'

        # PRs
        stale-pr-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        close-pr-message: 'Closing issue due to inactivity. Please reopen if needed'
        stale-pr-label: 'stale'