name: Verify GCR Login

on:
  schedule:
    - cron: "5 1 * * *" # daily

  workflow_dispatch:

jobs:
  login:
    name: Verify GCR Login
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@37a9333538a8350a13fe9d8fa03e0d4742a1ad2e # 0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
